name: mushaf_hafs
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.0
  scrollable_positioned_list: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/mushaf_photos_2/
    - images/
    

  fonts:
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf
        
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    
    - family: ScheherazadeNew
      fonts:
        - asset: fonts/ScheherazadeNew-Regular.ttf
        - asset: fonts/ScheherazadeNew-Bold.ttf
          weight: 700
  
